import styles from '@/styles/Home.module.css'
import { Inter } from '@next/font/google'
import { prisma } from '../server/db/client'
import React, { useState, useEffect } from 'react'
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Weather from '@/pages/api/weather.js';
import WriteArea from '@/component/write_area'

const inter = Inter({ subsets: ['latin'] })

export default function Home({posts}) {
  const apiKey = "4551243115444ba0a100a9567cd1b61d"
  const url = `https://newsapi.org/v2/everything?q=tesla&from=2022-12-17&sortBy=publishedAt&apiKey=${apiKey}`
  console.log(url);
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')

  // const handleSubmit = async (e) => {
  //   e.preventDefault()
  //   console.log({title, content})
  // }
  const handleSubmit = async (e) => {
    e.preventDefault()
    const res = await axios.post('/api/posts', { title, content })
    console.log(res.data)
  }

  return (
    <div
      className={`${styles.wrapper} ${styles.wrapper_home}`}
      >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper_main}>
          <h1 className={styles.ttl_page}>{}'s Diary</h1>

          <form
            className={styles.form}
            onSubmit={handleSubmit}
            >

            <div
              className={styles.container_diaryHead}
              >
              <input
                type="text"
                value={title}
                className={styles.ttl_diaryTitle}
                placeholder="Entry Title"
                onChange={(e) => setTitle(e.target.value)}
              />

              <div className={styles.box_date_weather}>
                <p class={styles.date}>DATE: {}</p>
                <Weather></Weather>
              </div>

            </div>

            <textarea
              value={content}
              className={styles.textarea_diaryContent}
              placeholder="Write about your day"
              onChange={(e) => setContent(e.target.value)}
            />

            <button
              className={`${styles.btn} ${styles.btn_diarySubmit}`}
              type="submit">Submit</button>
          </form>

          {posts.map((post) => (
            <div key={post.id}>
              <h2>{post.title}</h2>
              <p>{post.content}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const posts = await prisma.post.findMany()

  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
    }
  }
}
