// import styles from '@/styles/Home.module.css'
// import { prisma } from '@/server/db/client'
// import React, { useState, useEffect } from 'react'
// import axios from 'axios'
// import Head from 'next/head'
// import { PostsPage } from '@/pages/index'

// export default function Post({posts}) {
//   // const postId = 8;
//   // const post = posts.filter(post => post.id === postId)[0];

//   return (
//     <div
//       className={`${styles.wrapper} ${styles.wrapper_diary}`}
//       >
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <div className={styles.wrapper_main}>

//           <h1 className={styles.ttl_page}>{}'s Diary</h1>

//           <h2>{post.title}</h2>
//           <p>{post.content}</p>

//           {/* <Diary posts={posts}></Diary> */}

//           {posts.map((post) => (
//             <div key={post.id}>
//               <h2>{post.title}</h2>
//               <p>{post.content}</p>
//             </div>
//           ))}
//         </div>
//         </main>

//     </div>

//   )
// }
